code to create a baseline pandemic flu simulation

In [1]:
import pandas as pd
import numpy as np
from scipy.spatial import distance_matrix
print("Hello Github")

Hello Github

Initializing a dataframe of 1000 'people' in a 2-dimensional space with various attributes.

In [221]:
num_ppl = 1000

# various attributes of each person
per_num = []
x_pos = []
y_pos = []
infected = []
time_infected = []
recovered = []
immune = []
alive = []


#for person number, x_pos and y_pos, we set these for each individaul
size_min = 0
size_max = 500
for i in range(0,num_ppl):
    per_num.append(i)
    x_pos.append(np.random.randint(size_min,size_max))
    y_pos.append(np.random.randint(size_min,size_max))

    
# for infected, time_infected, and alive, we set these for all people to start with default values
infected = [0]*num_ppl
time_infected = [np.NaN]*num_ppl
alive = [1]*num_ppl
recovered = [0]*num_ppl
immune = [0]*num_ppl

population = pd.DataFrame(list(zip(per_num, x_pos, y_pos, infected, time_infected, recovered, immune, alive)),
                          columns = ["per_num", "x_pos", "y_pos", "infected",  
                                     "time_infected", "recovered", "immune","alive"])

print(population)

     per_num  x_pos  y_pos  infected  time_infected  recovered  immune  alive
0          0     17    143         0            NaN          0       0      1
1          1    411    330         0            NaN          0       0      1
2          2     75    159         0            NaN          0       0      1
3          3    262     80         0            NaN          0       0      1
4          4    348    231         0            NaN          0       0      1
..       ...    ...    ...       ...            ...        ...     ...    ...
995      995    469    199         0            NaN          0       0      1
996      996    101    384         0            NaN          0       0      1
997      997     46      7         0            NaN          0       0      1
998      998    123    248         0            NaN          0       0      1
999      999    275     62         0            NaN          0       0      1

[1000 rows x 8 columns]

Now we infect patient 0 in our pandemic

In [222]:
population.loc[0:0, 'infected'] = 1
population.loc[0:0, 'time_infected'] = 0
print(population)

     per_num  x_pos  y_pos  infected  time_infected  recovered  immune  alive
0          0     17    143         1            0.0          0       0      1
1          1    411    330         0            NaN          0       0      1
2          2     75    159         0            NaN          0       0      1
3          3    262     80         0            NaN          0       0      1
4          4    348    231         0            NaN          0       0      1
..       ...    ...    ...       ...            ...        ...     ...    ...
995      995    469    199         0            NaN          0       0      1
996      996    101    384         0            NaN          0       0      1
997      997     46      7         0            NaN          0       0      1
998      998    123    248         0            NaN          0       0      1
999      999    275     62         0            NaN          0       0      1

[1000 rows x 8 columns]

Setting up parameters and logs for the simulation

In [223]:
# Setting parameters for movement of our simulated people 
#the average person moves X units on the x axis and 10 units in the y axis. 
movement = 10
move_sdev = 5

Num_days = 50

#creating a log for the movement of patient zero (who we infect) & a random person (we'll pick person 25)

p_zero = {'day':[], 'xpos':[], 'ypos':[]}

p_rand = {'day':[], 'xpos':[], 'ypos':[]}

#creating a log for the simulation at each day

results = {'day':[], 'new_infections':[], 'infected':[], 'recovered':[], 'immune':[], 'alive':[]}


infected_array = population.loc[(population['infected'] == 1), 'x_pos':'y_pos']
pop_pos_array = population.loc[:, 'x_pos':'y_pos']

#Initial distance matrix
mtx0 = distance_matrix( pop_pos_array, infected_array)

for i in mtx0[0]:
    print(i)

0.0

Running the simulation

In [224]:
mtx = mtx0

for day in range(0, Num_days):
    
    new_infections = 0
    
    #loop through the population to determine status, and then change their position
    for p in range(0,num_ppl):
        
        #first determine if they were infected
        if population.loc[p,'infected'] == 0 and population.loc[p,'immune'] == 0:
            for infected_dist in mtx[p]: 
                if infected_dist <= 6 and population.loc[p,'infected'] == 0 : 
                    population.loc[p,'infected'] = 1
                    population.loc[p,'time_infected'] = day
                    new_infections += 1
                    #print('person {p} infected on day {d}'.format(p = p, d = day))
                    
        #next, for sick people, determine if they are better
        if (population.loc[p,'infected'] == 1 and population.loc[p,'alive'] == 1 and  (day - population.loc[p,'time_infected']) >14):
            population.loc[p,'infected'] = 0
            population.loc[p,'immune'] = 1
            population.loc[p,'recovered'] = 1
            
        #next, adjust movement (right now, everyone moves an average of 10 units each day)
        #the first part creates a random variable from a normal dist. the second determines if it is positive or negative
        x_move = np.random.normal(movement,move_sdev) * (-1 + 2*np.random.binomial(1,0.5))
        y_move = np.random.normal(movement,move_sdev) * (-1 + 2*np.random.binomial(1,0.5))
        
        if ((population.loc[p,'x_pos'] + x_move) < size_max) & ((population.loc[p,'x_pos'] + x_move) > size_min) :
            population.loc[p,'x_pos'] = population.loc[p,'x_pos'] + x_move
        else: 
            population.loc[p,'x_pos'] = population.loc[p,'x_pos'] - x_move
       
        if ((population.loc[p,'y_pos'] + y_move) < size_max) & ((population.loc[p,'y_pos'] + y_move) > size_min) :
            population.loc[p,'y_pos'] = population.loc[p,'y_pos'] + y_move
        else: 
            population.loc[p,'y_pos'] = population.loc[p,'y_pos'] - y_move
        
        
        #now we need to make a new distance matrix
        infected_array_day = population.loc[(population['infected'] == 1), 'x_pos':'y_pos']
        pop_pos_array_day = population.loc[:, 'x_pos':'y_pos']

        #updated distance matrix
        mtx = distance_matrix( pop_pos_array_day, infected_array_day)
        
    #update the log each day: 
    #path of patient zero
    p_zero['day'].append(day)
    p_zero['xpos'].append(population.loc[0,'x_pos'])
    p_zero['ypos'].append(population.loc[0,'y_pos'])
    
    #path of a random person (25)
    p_rand['day'].append(day)
    p_rand['xpos'].append(population.loc[25,'x_pos'])
    p_rand['ypos'].append(population.loc[25,'y_pos'])
    
    #overall results
    
    tot_infected = sum(population['infected'] == 1)
    tot_recovered = sum(population['recovered'] == 1)
    tot_immune = sum(population['immune'] == 1)
    tot_alive = sum(population['alive'] == 1)
    results['day'].append(day)
    results['new_infections'].append(new_infections)
    results['infected'].append(tot_infected)
    results['recovered'].append(tot_recovered)     
    results['immune'].append(tot_immune)  
    results['alive'].append(tot_alive)  
    
    print('Day {0} | {1} newly infected | {2} total infected | {3} have recovered'.format(day, new_infections, tot_infected, tot_recovered))

Day 0 | 0 newly infected | 1 total infected | 0 have recovered
Day 1 | 2 newly infected | 3 total infected | 0 have recovered
Day 2 | 1 newly infected | 4 total infected | 0 have recovered
Day 3 | 0 newly infected | 4 total infected | 0 have recovered
Day 4 | 2 newly infected | 6 total infected | 0 have recovered
Day 5 | 5 newly infected | 11 total infected | 0 have recovered
Day 6 | 7 newly infected | 18 total infected | 0 have recovered
Day 7 | 9 newly infected | 27 total infected | 0 have recovered
Day 8 | 1 newly infected | 28 total infected | 0 have recovered
Day 9 | 5 newly infected | 33 total infected | 0 have recovered
Day 10 | 10 newly infected | 43 total infected | 0 have recovered
Day 11 | 7 newly infected | 50 total infected | 0 have recovered
Day 12 | 8 newly infected | 58 total infected | 0 have recovered
Day 13 | 7 newly infected | 65 total infected | 0 have recovered
Day 14 | 8 newly infected | 73 total infected | 0 have recovered
Day 15 | 11 newly infected | 83 total infected | 1 have recovered
Day 16 | 10 newly infected | 91 total infected | 3 have recovered
Day 17 | 9 newly infected | 99 total infected | 4 have recovered
Day 18 | 9 newly infected | 108 total infected | 4 have recovered
Day 19 | 6 newly infected | 112 total infected | 6 have recovered
Day 20 | 10 newly infected | 117 total infected | 11 have recovered
Day 21 | 13 newly infected | 123 total infected | 18 have recovered
Day 22 | 11 newly infected | 125 total infected | 27 have recovered
Day 23 | 12 newly infected | 136 total infected | 28 have recovered
Day 24 | 13 newly infected | 144 total infected | 33 have recovered
Day 25 | 18 newly infected | 152 total infected | 43 have recovered
Day 26 | 10 newly infected | 155 total infected | 50 have recovered
Day 27 | 7 newly infected | 154 total infected | 58 have recovered
Day 28 | 12 newly infected | 159 total infected | 65 have recovered
Day 29 | 11 newly infected | 162 total infected | 73 have recovered
Day 30 | 13 newly infected | 164 total infected | 84 have recovered
Day 31 | 20 newly infected | 174 total infected | 94 have recovered
Day 32 | 18 newly infected | 183 total infected | 103 have recovered
Day 33 | 19 newly infected | 193 total infected | 112 have recovered
Day 34 | 26 newly infected | 213 total infected | 118 have recovered
Day 35 | 18 newly infected | 221 total infected | 128 have recovered
Day 36 | 27 newly infected | 235 total infected | 141 have recovered
Day 37 | 14 newly infected | 238 total infected | 152 have recovered
Day 38 | 21 newly infected | 247 total infected | 164 have recovered
Day 39 | 12 newly infected | 246 total infected | 177 have recovered
Day 40 | 19 newly infected | 247 total infected | 195 have recovered
Day 41 | 13 newly infected | 250 total infected | 205 have recovered
Day 42 | 8 newly infected | 251 total infected | 212 have recovered
Day 43 | 16 newly infected | 255 total infected | 224 have recovered
Day 44 | 20 newly infected | 264 total infected | 235 have recovered
Day 45 | 14 newly infected | 265 total infected | 248 have recovered
Day 46 | 20 newly infected | 265 total infected | 268 have recovered
Day 47 | 16 newly infected | 263 total infected | 286 have recovered
Day 48 | 15 newly infected | 259 total infected | 305 have recovered
Day 49 | 20 newly infected | 253 total infected | 331 have recovered

In [225]:
pd.DataFrame(p_zero)

    day       xpos        ypos
0     0   4.357491  152.852637
1     1  11.942209  163.285989
2     2  33.828228  152.823959
3     3  22.031059  141.001388
4     4   6.470687  145.760079
5     5  28.893713  137.265602
6     6  41.532203  143.842817
7     7  59.940808  155.952162
8     8  75.738796  178.160466
9     9  67.419683  173.340820
10   10  80.332981  187.399264
11   11  83.602050  196.059846
12   12  75.169312  207.344912
13   13  72.375623  221.009849
14   14  55.537617  210.001951
15   15  68.257084  195.166753
16   16  61.674610  205.758026
17   17  65.957574  219.624812
18   18  76.950174  232.765818
19   19  90.042929  246.598270
20   20  81.756824  228.429248
21   21  69.915403  221.885875
22   22  56.275284  219.141025
23   23  61.847055  201.690679
24   24  50.535958  190.813447
25   25  38.534151  207.858565
26   26  25.425245  189.613013
27   27  11.356354  196.059290
28   28  25.024243  190.377366
29   29  18.524428  178.148272
30   30  29.780169  181.129010
31   31  40.806209  176.292225
32   32  29.286940  196.658470
33   33  12.610704  189.273459
34   34  15.595531  203.430070
35   35  20.797828  203.767150
36   36  30.972376  190.602909
37   37  19.749826  186.883398
38   38  10.542275  190.566763
39   39  25.882649  181.234103
40   40  11.056179  172.602927
41   41  19.916679  187.821811
42   42   7.260192  171.457044
43   43   4.042629  170.758590
44   44   3.278820  184.880801
45   45   8.153747  194.747881
46   46  14.613440  201.996615
47   47  21.238620  219.336322
48   48  33.350574  223.998488
49   49  54.943351  216.173062

In [226]:
pd.DataFrame(results)

    day  new_infections  infected  recovered  immune  alive
0     0               0         1          0       0   1000
1     1               2         3          0       0   1000
2     2               1         4          0       0   1000
3     3               0         4          0       0   1000
4     4               2         6          0       0   1000
5     5               5        11          0       0   1000
6     6               7        18          0       0   1000
7     7               9        27          0       0   1000
8     8               1        28          0       0   1000
9     9               5        33          0       0   1000
10   10              10        43          0       0   1000
11   11               7        50          0       0   1000
12   12               8        58          0       0   1000
13   13               7        65          0       0   1000
14   14               8        73          0       0   1000
15   15              11        83          1       1   1000
16   16              10        91          3       3   1000
17   17               9        99          4       4   1000
18   18               9       108          4       4   1000
19   19               6       112          6       6   1000
20   20              10       117         11      11   1000
21   21              13       123         18      18   1000
22   22              11       125         27      27   1000
23   23              12       136         28      28   1000
24   24              13       144         33      33   1000
25   25              18       152         43      43   1000
26   26              10       155         50      50   1000
27   27               7       154         58      58   1000
28   28              12       159         65      65   1000
29   29              11       162         73      73   1000
30   30              13       164         84      84   1000
31   31              20       174         94      94   1000
32   32              18       183        103     103   1000
33   33              19       193        112     112   1000
34   34              26       213        118     118   1000
35   35              18       221        128     128   1000
36   36              27       235        141     141   1000
37   37              14       238        152     152   1000
38   38              21       247        164     164   1000
39   39              12       246        177     177   1000
40   40              19       247        195     195   1000
41   41              13       250        205     205   1000
42   42               8       251        212     212   1000
43   43              16       255        224     224   1000
44   44              20       264        235     235   1000
45   45              14       265        248     248   1000
46   46              20       265        268     268   1000
47   47              16       263        286     286   1000
48   48              15       259        305     305   1000
49   49              20       253        331     331   1000

In [186]:
print(np.random.normal(movement,move_sdev)*(-1 + 2*np.random.binomial(1,0.5)))

-11.571629216348247